CityOfZion/neo-mon

src/assets/json/mainnet.json

Reverts CityOfZion/neo-mon#4
These Nodes are no longer on Network.

Revert "Update mainnet.json with O3 nodes"

---

docs/assets/mainnet.json

neo-cli 2.7.1
* seed1.redpulse.com
* seed2.redpulse.com
neo-python json-rpc seeds
* pyrpc1.redpulse.com
* pyrpc2.redpulse.com

Added Red Pulse seeds

---

src/assets/json/mainnet.json

Updated to use FQDN vs IP for Treatail nodes.  DNS propagation in progress...
Moved node 3 to Illinois for more geo-distribution

Updated Treatail NEO 2.7.1 USA Seeds with FQDN

---

docs/assets/mainnet.json

neo-cli seeds with SSL
* https://seed1.redpulse.com:10331
* https://seed2.redpulse.com:10331
python JSON-RPC seeds with SSL
* https://pyrpc1.redpulse.com:10331
* https://pyrpc2.redpulse.com:10331
Python REST api with SSL:
* https://pyapi1.redpulse.com
* https://pyapi2.redpulse.com

RedPulse Seeds with SSL

---

docs/assets/mainnet.json
src/assets/icons/tsvg/flag-gb.svg
src/assets/icons/tsvg/flag-nl.svg

* Adding Narrative JSON-RPC neo-python nodes.

Add Narrative Nodes

---

docs/assets/mainnet.json

* Adding Narrative REST neo-python nodes.

Add Narrative REST Nodes

---

docs/assets/mainnet.json

Two seeds from the Coinage team.

coinage seeds for Frankfurt and London

---

src/app/netstats.factory.js
src/index.html

- Fix the initial page title
- Set the initial block duration to 15 seconds
- Make the page title update automatically
Closes CityOfZion/neo-mon/#41

Make the page title update automatically

---

docs/assets/mainnet.json
src/assets/icons/tsvg/flag-ch.svg

I am running a community node that I plan to keep updated as much as possible. I have been following NEO development for 8 months and want to contribute to the network with this seed node. 
8 Core
16 Threads
32 GB RAM
Running NEO-CLI 2.7.2 on Windows Server 2012 R2
I plan on keeping running it as long as I can.

Community Node

---

docs/assets/mainnet.json

We're running an ICO based on NEO (Concierge.io), and want to contribute to the network with below nodes:
- AWS t2.large (2 vCPU, 8GB RAM)
- OS: Red Hat Enterprise Linux 7.4
- NEO-CLI 2.7.1

Community nodes from Concierge Team

---

docs/assets/mainnet.json

I updated the domain name to replace previous dydns

Update domain name

---

docs/assets/mainnet.json

Contributing 4 nodes on the behalf of Switcheo Network.

Add switcheo nodes

---

docs/assets/mainnet.json

Removing germany node and adding a second India node for Amchart.io

Fixing conflicts

---

docs/assets/mainnet.json

Pulling Treatail seeds 3 and 4 out of pool for now due to issues, seeds 1 and 2 will remain.

Removing Treatail Seeds 3 and 4

---

docs/assets/mainnet.json

Amchart is removing some neo nodes

Update mainnet.json to remove some Amchart nodes

---

docs/assets/mainnet.json

Modified node deployment for Bridge Protocol

Update neo-cli node paths

---

docs/assets/mainnet.json

This is a permanent new node running in the UK.

Update mainnet.json to add new rustylogic node

---

docs/assets/mainnet.json

- Removed http seed1,seed2,seed3 from o3 and replaced it with https://seed.o3nodeorg:10331

Updated o3node.org

---

docs/assets/mainnet.json

Contributing 1 new node on the behalf of Switcheo Network.

Add switcheo node

---

docs/assets/mainnet.json

Remove amchart node from mainnet.json

Update mainnet.json to remove amchart node

---

docs/assets/mainnet.json

only use HTTPS for redpulse seeds

mainnet.json: red pulse only HTTPS

---

docs/assets/mainnet.json

Add neoeconomy node

---

docs/assets/mainnet.json

add plutology node

---

docs/assets/testnet.json

Update seed nodes of NGD

---

docs/assets/testnet.json

Fix the wrong port of NGD

---

docs/assets/mainnet.json

Domain update

---

docs/assets/mainnet.json

Retiring the notifications servers as communicated 3 months ago and reminded 1 month ago.

Remove notifications servers

---

docs/assets/mainnet.json
docs/assets/testnet.json

Seeds from neo.org are unavailable now.

remove unused neo.org seeds
